baseURL = "https://codegenie.nsono.net/"
languageCode = "en-us"
title = "CodeGenie"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_button_link2 = 'https://marketplace.visualstudio.com/items?itemName=astalwick.codegenie'
  homepage_button_text2 = 'Get CodeGenie!'
  homepage_image = '/images/recording.webm'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "CodeGenie is your ChatGPT-powered coding assistant."
    meta_og_title = "CodeGenie"
    meta_og_type = "website"
    meta_og_url = "https://codegenie.nsono.net"
    meta_og_image = "https://codegenie.nsono.net/images/logo.png"
    meta_og_description = "CodeGenie is your ChatGPT-powered coding assistant."
    meta_twitter_card = "summary"
    meta_twitter_site = "@astalwick"
    meta_twitter_creator = "@astalwick"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"

[deployment]
# Set the destination path on S3, including your bucket name
[[deployment.targets]]
  name = "s3"
  URL = "s3://codegenie.nsono.net"

  # Configure which files to deploy
  [deployment.targets.s3]
    bucket = "codegenie.nsono.net"
    cloudfront_distribution_id = "E6P84L5XVTEEO"
    acl = "public-read"
    cache_control_header = "public, max-age=86400, must-revalidate"
    # Add any other S3-specific configuration options here
